@DotNet8MiniProjectApi.SampleBackgroundJobHangfire_HostAddress = http://localhost:5072

GET {{DotNet8MiniProjectApi.SampleBackgroundJobHangfire_HostAddress}}/weatherforecast/
Accept: application/json

###
